<?php
/**
 * @file
 * Support for dubious legal agreement during user registration.
 */

/**
 * Implements hook_form_alter().
 */
function legalagree_form_alter(&$form, &$form_state, $form_id)
{

    // check to see if the form is the user registration or user profile form
    // if not then return and don't do anything
    if (!($form_id == 'user_register_form' || $form_id == 'user_profile_form')) {
        return;
    }

    // add a new validate function to the user form to handle the legal agreement
    $form['#validate'][] = 'legalagree_user_form_validate';

    // add a field set to wrap the legal agreement
    $form['account']['legal_agreement'] = [
        '#type' => 'fieldset',
        '#title' => t('Legal agreement')
    ];

    // add the legal agreement radio buttons
    $form['account']['legal_agreement']['decision'] = [
        '#type' => 'radios',
        '#description' => t('By registering at %site-name, you agree that at any time, we (or our surly, brutish henchmen) may enter your place of residence and smash your belongings with a ball-peen hammer.',
            ['%site-name' => variable_get('site_name', 'drupal')]),
        '#default_value' => 0,
        '#options' => [
            t('I disagree'),
            t('I agree')
        ]
    ];
}

/**
 * Form validation handler for the current password on the user_account_form()
 *
 * @param $form
 * @param $form_state
 *
 * @see user_account_form()
 */
function legalagree_user_form_validate($form, &$form_state){

    global $user;

    // Did user agree?
    if($form_state['input']['decision'] != 1){
        form_set_error('decision', t('You must agree to the Legal Agreement before registration can be completed.'));
    }else{
        watchdog('user', t('User %user agreed to legal terms', ['%user' => $user->name]));
    }
}
